### ISSUE TITLE
How to get a activity getstream.io activity using foreign_id or any custom parameter?

### ISSUE THREAD

**Issue by sunnymopada** [GetStream/Stream-Example-Android#4]
Hi,

How to get or filter an activity using foreign_id or any custom parameter I gave while creating in android client?

I sent this question to getstream.io team. But they replied that they are not giving filters other than pagination.

So is there any other workaround for this?

If not, getstream.io team, Please implement that

**Comment by tbarbugli** [comment]
API does not allow you to filter by attributes (except for activity_id)

**Comment by sunnymopada** [comment]
@tbarbugli Okay how can I get an activity by activity_id?

And I can give custom activity_id while creating it right?

**Comment by sunnymopada** [comment]
@tbarbugli @iandouglas Can you guys reply please?. I blocked there?

**Comment by tbarbugli** [comment]
you can filter feeds by activity_id (same way you do for pagination) but you can't pick activity_ids, they are generated on Stream's side.
